//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt;
        ///&lt;Start&gt;-&gt;&lt;File&gt;&apos;EOF&apos;
        ///File.Build(new(Root));
        ///return File;
        ///
        ///&gt;&gt;&gt;
        ///&lt;Space&gt;-&gt;&apos; &apos;
        ///
        ///&gt;&gt;&gt;
        ///&lt;Space&gt;-&gt;
        ///
        ///&gt;&gt;&gt;
        ///&lt;File&gt;-&gt;&lt;FileHeader&gt;&lt;FileBody&gt;
        ///
        ///&gt;&gt;&gt;
        ///&lt;FileHeader&gt;-&gt;
        ///
        ///&gt;&gt;&gt;
        ///&lt;FileHeader&gt;-&gt;&lt;FileHeader&gt;&lt;UsingNamespace&gt;&lt;Space&gt;
        ///
        ///&gt;&gt;&gt;
        ///&lt;UsingNamespace&gt;-&gt;&apos;using&apos;&apos; &apos;&lt;NamespaceName&gt;&apos;;&apos;
        ///UsingNamespace();
        ///
        ///&gt;&gt;&gt;
        ///&lt;NamespaceName&gt;-&gt;&apos;Symbol&apos;
        ///NamespaceName=new();
        ///NamespaceName.Add(Values[0].Value_String);
        ///
        ///&gt;&gt;&gt;
        ///&lt;NamespaceName&gt;-&gt;&lt;NamespaceName&gt;&apos;.&apos;&apos;Symbol&apos;
        ///NamespaceName.Add(Values[2].Value_String);
        ///
        ///&gt;&gt;&gt;
        ///&lt;FileBody&gt;- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CSharp_LALR {
            get {
                return ResourceManager.GetString("CSharp_LALR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File=new();
        ///Root=new();
        ///Root.LoadAssembly(typeof(string).Assembly,typeof(Console).Assembly);
        ///Root.Lock(); 的本地化字符串。
        /// </summary>
        public static string CSharp_LALR_Init {
            get {
                return ResourceManager.GetString("CSharp_LALR_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 private ParsingFile File;
        ///private List&lt;string&gt; NamespaceName;
        ///private void UsingNamespace()
        ///{
        ///    string name=string.Join(&quot;.&quot;, NamespaceName);
        ///    if (File.Usings.ContainsKey(name)) File.Errors.Add($&quot;Found Using Conflict&quot;);
        ///    else File.Usings[name] = NamespaceName.ToArray();
        ///}
        ///private void DefineNamespace()
        ///{
        ///    string[] names = NamespaceName.ToArray();
        ///    Namespace.Name=string.Join(&quot;.&quot;,NamespaceName);
        ///    for(int i=NamespaceName.Count-2;i&gt;=0;i--)
        ///    {
        ///        UserNamespace @namespace = n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CSharp_LALR_Method {
            get {
                return ResourceManager.GetString("CSharp_LALR_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt;瀛楃
        ///[\x20\x21\x23-\x26\x28-\x5B\x5D-\xFFFF]
        ///token = Values[0];
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\0
        ///token = &apos;\0&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\a
        ///token = &apos;\a&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\b
        ///token = &apos;\b&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\t
        ///token = &apos;\t&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\n
        ///token = &apos;\n&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\v
        ///token = &apos;\v&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\f
        ///token = &apos;\f&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\r
        ///token = &apos;\r&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\&quot;
        ///token = &apos;\&quot;&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\\\
        ///token = &apos;\\&apos;;
        ///
        ///&gt;&gt;&gt;杞箟瀛楃
        ///\\u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]
        ///token = (char)int.Parse(Value.ToString()[2..5],Sys [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CSharp_String_Token {
            get {
                return ResourceManager.GetString("CSharp_String_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt;鍛藉悕
        ///[a-zA-Z][0-9a-zA-Z_]*
        ///token = Keys.Contains(Value.ToString()) ? (new(Value.ToString())) : Token.Symbol(Value.ToString());
        ///
        ///&gt;&gt;&gt;寮哄埗鍛藉悕
        ///@[0-9a-zA-Z]+
        ///if(Keys.Contains(Value.ToString()[1..]))token = Token.Symbol(Value.ToString()[1..]);else return Error(symbol);
        ///
        ///&gt;&gt;&gt;闂撮殧
        ///[\t\n\r\s]+
        ///token = new(&quot; &quot;);
        ///
        ///&gt;&gt;&gt;绗﹀彿
        ///([\+\-\*/%&lt;&gt;=!^@\|&amp;;,\(\)\[\]{}?:.]|&lt;=|&gt;=|==|!=|\+\+|\-\-|\+=|\-=|\|\||&amp;&amp;|.?|=&gt;)
        ///token = new(Value.ToString());
        ///
        ///&gt;&gt;&gt;鏈夌鍙锋暣鏁?
        ///(|\-)0*(0|[1-9][0-9]*)
        ///token = Token.Int32(int.Parse(Value. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CSharp_Token {
            get {
                return ResourceManager.GetString("CSharp_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 private static readonly HashSet&lt;string&gt; Keys=new(new string[]{
        ///	&quot;public&quot;,
        ///	&quot;private&quot;,
        ///	&quot;class&quot;,
        ///	&quot;int&quot;,
        ///	&quot;void&quot;,
        ///	&quot;using&quot;,
        ///	&quot;namespace&quot;,
        ///	&quot;static&quot;
        ///});
        ///private int CharState;
        ///public char? GetChar()
        ///{
        ///    char token=&apos;\0&apos;;
        ///    int value=0;
        ///    while (true)
        ///    {
        ///        char symbol = Peek();
        ///        switch (CharState)
        ///        {
        ///            case 0:
        ///                if (symbol is &apos;\0&apos;) return null;
        ///                else if (symbol is &gt;= &apos; &apos; and &lt;= &apos;!&apos; or &gt;= &apos;#&apos; and &lt;= &apos;&amp;&apos; or &gt;= &apos;(&apos; and &lt;= &apos;[&apos; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string CSharp_Token_Method {
            get {
                return ResourceManager.GetString("CSharp_Token_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt;Terminal
        ///&apos;[\x20-\x26\x28-\xFFFF]*&apos;
        ///token=Token.Terminal(Value.ToString()[1..^1]);
        ///
        ///&gt;&gt;&gt;Define Symbol
        ///\-&gt;
        ///token=new(&quot;Define&quot;);
        ///
        ///&gt;&gt;&gt;Variable
        ///&lt;[\x20-\x3D\x3F-\xFFFF]*&gt;
        ///token=Token.Variable(Value.ToString()[1..^1]); 的本地化字符串。
        /// </summary>
        public static string LALR_Token {
            get {
                return ResourceManager.GetString("LALR_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public class _Parser:IParser&lt;TToken, TValue, TResult&gt;
        ///{
        ///    public static readonly int[,] VariableTable={
        ///        //VariableTable
        ///    };
        ///    public override TResult Parse(ITokenizer&lt;TToken&gt; tokenizer)
        ///    {
        ///        Init();
        ///        //Init
        ///        TToken token = tokenizer.Get();
        ///        int symbol = 0;
        ///        bool mode = true;
        ///        TToken[] tokens;
        ///        TValue[] values;
        ///        TValue value;
        ///        while (true)
        ///        {
        ///            if (mode)
        ///            {
        ///                switch (St [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Parser {
            get {
                return ResourceManager.GetString("Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //class _Parser:public IParser&lt;TToken,TResult,TValues&gt;
        /////using _MyBase=IParser&lt;TToken,TResult,TValues&gt;;
        ///
        ///int VariableTable//VT
        ///
        /////Method
        ///
        ///_Parser::_Parser()
        ///	:_MyBase()
        ///{
        ///}
        ///
        ///shared_ptr&lt;TResult&gt; _Parser::Parse(shared_ptr&lt;ITokenizer&lt;TToken&gt;&gt; tokenizer)
        ///{
        ///	Init();
        ///	_MyBase &amp;Parser = *this;
        ///	//Init
        ///
        ///	int symbol = 0;
        ///	bool mode = true;
        ///	shared_ptr&lt;TToken&gt; token = tokenizer-&gt;Get();
        ///	Array&lt;shared_ptr&lt;TToken&gt;&gt; tokens(0);
        ///	while (true)
        ///	{
        ///		if (mode)
        ///		{
        ///		    switch (StateStack.top())
        ///    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ParserCPP {
            get {
                return ResourceManager.GetString("ParserCPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //class _Parser:public IParser&lt;TToken,TResult,TValues&gt;
        /////using _MyBase=IParser&lt;TToken,TResult,TValues&gt;;
        ///
        ///int _ParserVariableTable//VT
        ///
        /////Method
        ///
        ///shared_ptr&lt;TResult&gt; _Parser::Parse(shared_ptr&lt;ITokenizer&lt;TToken&gt;&gt; tokenizer)
        ///{
        ///	Init();
        ///	_MyBase &amp;Parser = *this;
        ///	//Init
        ///
        ///	int symbol = 0;
        ///	bool mode = true;
        ///	shared_ptr&lt;TToken&gt; token = tokenizer-&gt;get();
        ///	vector&lt;shared_ptr&lt;TToken&gt;&gt; tokens;
        ///	while (true)
        ///	{
        ///		if (mode)
        ///		{
        ///		    switch (m_StateStack.top())
        ///            {
        ///                //Shif [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ParserCPPshort {
            get {
                return ResourceManager.GetString("ParserCPPshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public class _Parser:IParser&lt;TToken, TResult&gt;
        ///{
        ///    //TypeStacks
        ///    public static readonly int[,] VariableTable={
        ///        //VariableTable
        ///    };
        ///    public override TResult Parse(ITokenizer&lt;TToken&gt; tokenizer)
        ///    {
        ///        Init();
        ///        //Init
        ///        TToken token = tokenizer.Get();
        ///        int symbol = 0;
        ///        bool mode = true;
        ///        TToken[] tokens;
        ///        while (true)
        ///        {
        ///            if (mode)
        ///            {
        ///                switch (StateStack.Peek())
        ///                {
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ParserTyped {
            get {
                return ResourceManager.GetString("ParserTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt;
        ///&lt;Start&gt;-&gt;&lt;R&gt;&apos;EOF&apos;
        ///return new(Values[0],CharBlocks.ToArray());
        ///
        ///&gt;&gt;&gt;
        ///&lt;R&gt;-&gt;
        ///value=new RE_Block();
        ///
        ///&gt;&gt;&gt;
        ///&lt;R&gt;-&gt;&lt;R&gt;&lt;S&gt;
        ///value=Values[0];
        ///(value as RE_Block).Values.Add(Values[1]);
        ///
        ///&gt;&gt;&gt;
        ///&lt;R&gt;-&gt;&lt;R&gt;&lt;C&gt;
        ///value=Values[0];
        ///(value as RE_Block).Values.Add(Values[1]);
        ///
        ///&gt;&gt;&gt;
        ///&lt;C&gt;-&gt;&lt;S&gt;&apos;*&apos;
        ///value=new RE_Closure(Values[0]);
        ///
        ///&gt;&gt;&gt;
        ///&lt;C&gt;-&gt;&lt;S&gt;&apos;+&apos;
        ///value=new RE_PositiveClosure(Values[0]);
        ///
        ///&gt;&gt;&gt;
        ///&lt;S&gt;-&gt;&apos;Char&apos;
        ///value=new RE_Char(Values[0].Value);
        ///CharBlocks.Add(value);
        ///
        ///&gt;&gt;&gt;
        ///&lt;S&gt;-&gt;&lt;OB&gt;
        ///value=Values[0];
        ///
        ///&gt;&gt;&gt;
        ///&lt;S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RE_LALR {
            get {
                return ResourceManager.GetString("RE_LALR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CharBlocks = new(); 的本地化字符串。
        /// </summary>
        public static string RE_LALR_Init {
            get {
                return ResourceManager.GetString("RE_LALR_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 private List&lt;IRE_Block&gt; CharBlocks; 的本地化字符串。
        /// </summary>
        public static string RE_LALR_Method {
            get {
                return ResourceManager.GetString("RE_LALR_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt; Unicode characters excepts EOF and keywords
        ///[\x01-\x27\x2C\x2E-\x5A\x5E-\x7B\x7D\x7E-\xFFFF]
        ///token=new Token(Value[0]);
        ///
        ///&gt;&gt;&gt; keywords
        ///[\[\-\]\(\|\)\*\+\\]
        ///token=new Token(Value);
        ///
        ///&gt;&gt;&gt; escape char of keywords
        ///\\[\[\-\]\(\|\)\*\+\\]
        ///token=new Token(Value[1]);
        ///
        ///&gt;&gt;&gt; decimal representation of a character code
        ///\\d[0-9]+
        ///token=new Token((char)int.Parse(Value.ToString()[2..]));
        ///
        ///&gt;&gt;&gt; hex representation of a character code
        ///\\x[0-9a-zA-Z]+
        ///token=new Token((char)int.Parse(Value.ToString()[2..],Sys [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RE_Token {
            get {
                return ResourceManager.GetString("RE_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace Test
        ///{
        ///    public class Program
        ///    {
        ///        public static int MainVersion;
        ///        public static int MajorVersion;
        ///        public static int SubVersion;
        ///        public void Test()
        ///        {
        ///            Console.WriteLine(0);
        ///            Console.WriteLine(123);
        ///            Console.WriteLine(-987);
        ///            Console.WriteLine(0x12aF);
        ///            Console.WriteLine(0b101);
        ///            Console.WriteLine(0.1e001);
        ///            Console.WriteLine(-12.1e-12);
        ///            [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Test_Code {
            get {
                return ResourceManager.GetString("Test_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt;
        ///&lt;Start&gt;-&gt;&lt;S&gt;&apos;EOF&apos;
        ///
        ///&gt;&gt;&gt;
        ///&lt;S&gt;-&gt;&apos;0&apos;&lt;S&gt;&apos;0&apos;
        ///
        ///&gt;&gt;&gt;
        ///&lt;S&gt;-&gt;&apos;1&apos;&lt;S&gt;&apos;1&apos;
        ///
        ///&gt;&gt;&gt;
        ///&lt;S&gt;-&gt;&apos;0&apos;&apos;1&apos;
        /// 的本地化字符串。
        /// </summary>
        public static string Test_LALR {
            get {
                return ResourceManager.GetString("Test_LALR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Tokenizer::_Tokenizer(int length)
        ///{
        ///
        ///}
        ///
        /////Method
        ///
        ///shared_ptr&lt;TToken&gt; _Tokenizer::Get()
        ///{
        ///	shared_ptr&lt;TToken&gt; token;
        ///	while(true)
        ///	{
        ///		wchar_t symbol = Peek();
        ///		switch (State)
        ///		{
        ///			//StateCode
        ///			default:
        ///				return Error(symbol);
        ///		}
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        public static string TokenizerCPP {
            get {
                return ResourceManager.GetString("TokenizerCPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Tokenizer::_Tokenizer(int length)
        ///{
        ///
        ///}
        ///
        /////Method
        ///
        ///shared_ptr&lt;TToken&gt; _Tokenizer::get()
        ///{
        ///	shared_ptr&lt;TToken&gt; token;
        ///	while(true)
        ///	{
        ///		wchar_t symbol = Peek();
        ///		switch (m_State)
        ///		{
        ///			//StateCode
        ///			default:
        ///				return Error(symbol);
        ///		}
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        public static string TokenizerCPPshort {
            get {
                return ResourceManager.GetString("TokenizerCPPshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public class _Tokenizer:ITokenizer&lt;TToken&gt;
        ///{
        ///	public _Tokenizer(Encoding encoding,int length=1&lt;&lt;10):base(encoding,length){}
        ///	public _Tokenizer(int length = 1 &lt;&lt; 10) : base(length) { }
        ///	public override TToken Get()
        ///	{
        ///		TToken token;
        ///		while(true)
        ///		{
        ///			char symbol = Peek();
        ///			switch (State)
        ///			{
        ///				//StateCode
        ///				default:
        ///					return Error(symbol);
        ///			}
        ///		}
        ///	}
        ///	//Method
        ///} 的本地化字符串。
        /// </summary>
        public static string TokenizerCSharp {
            get {
                return ResourceManager.GetString("TokenizerCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 class _Tokenizer(Enumerable[Token]):
        ///	def __init__(self,stream:Enumerable[int]):
        ///		self.Stream=stream
        ///		self.State=0
        ///		self.Result=Token(&quot;_Empty&quot;)
        ///		self.Map=[//Map]
        ///		self.Symbol=self.Stream.Get() if self.Stream.MoveNext() else None
        ///		self.Value=&quot;&quot;
        ///	//Methods
        ///	//Functions
        ///	def ReturnToken(self,token:Token)-&gt;Tuple[bool,Token]:
        ///		self.State = 0
        ///		self.Value =0
        ///		return True,token
        ///	def Push(self,symbol):
        ///		self.Value+=symbol
        ///	def Peek(self)-&gt;int:
        ///		return self.Symbol
        ///	def Pop(self)-&gt;Tuple[bo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TokenizerPython {
            get {
                return ResourceManager.GetString("TokenizerPython", resourceCulture);
            }
        }
    }
}
