namespace CSharpScript.File
{
	public enum NativeType
	{
		NATIVE_TYPE_BOOLEAN = 2,
		NATIVE_TYPE_I1 = 3,
		NATIVE_TYPE_U1 = 4,
		NATIVE_TYPE_I2 = 5,
		NATIVE_TYPE_U2 = 6,
		NATIVE_TYPE_I4 = 7,
		NATIVE_TYPE_U4 = 8,
		NATIVE_TYPE_I8 = 9,
		NATIVE_TYPE_U8 = 10,
		NATIVE_TYPE_R4 = 11,
		NATIVE_TYPE_R8 = 12,
		NATIVE_TYPE_LPSTR = 20,
		NATIVE_TYPE_LPWSTR = 21,
		NATIVE_TYPE_INT = 0x1F,
		NATIVE_TYPE_UINT = 0x20,
		NATIVE_TYPE_FUNC = 38,
		NATIVE_TYPE_ARRAY = 42,
		NATIVE_TYPE_MAX = 80
	}
}
