using System;
namespace CSharpScript.File
{
	[Flags]
	public enum RuntimeFlag
	{
		COMIMAGE_FLAGS_ILONLY = 0x1,
		COMIMAGE_FLAGS_32BITREQUIRED = 0x2,
		COMIMAGE_FLAGS_STRONGNAMESIGNED = 0x8,
		COMIMAGE_FLAGS_NATIVE_ENTRYPOINT = 0x10,
		COMIMAGE_FLAGS_TRACKDEBUGDATA = 0x10000
	}
}
