//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 @using@:using
        ///@Assemble@:~[\.\;\ ]
        ///@Assembles@:{@Assemble@,\.} 的本地化字符串。
        /// </summary>
        public static string CSharp {
            get {
                return ResourceManager.GetString("CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @Name@:\@~[\@]\@
        ///@Space@:\ 
        ///@Key@:\&lt;{@Symbol@}\&gt;
        ///@Symbol.Special@:[\\\@\(\)\[\]\{\}\&lt;\&gt;\~\|\,\.\:\;\ ]
        ///@Symbol@:([abcdefghijklmnopqrstuvwxyz]|(\\@Symbol.Special@))
        ///@Symbol.Group@:\[{@Symbol@}\]
        ///@Value@:\~@Symbol.Group@
        ///@IParser@:(@Name@|@Symbol@|@Symbol.Group@|@Value@|@Option@|@Join.1@|@Join.2@|@Space@|@Key@|@Stream@)
        ///@Option@:\({@IParser@,\|}\)
        ///@Stream@:\({@IParser@}\)
        ///@Join.1@:\{@IParser@\}
        ///@Join.2@:\{@IParser@\,@IParser@\}
        ///@Parser@:@Name@\:{@IParser@}
        ///@Parsers@:{@Parser@, } 的本地化字符串。
        /// </summary>
        public static string Grammar_Parser {
            get {
                return ResourceManager.GetString("Grammar_Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot; &quot;:{
        ///		&quot;type&quot;:&quot;Space&quot;,
        ///		&quot;min&quot;:0,
        ///		&quot;select&quot;:false
        ///	},
        ///	&quot;bool&quot;:{
        ///		&quot;type&quot;:&quot;Option&quot;,
        ///		&quot;options&quot;:[
        ///			{
        ///				&quot;type&quot;:&quot;Key&quot;,
        ///				&quot;key&quot;:&quot;false&quot;
        ///			},
        ///			{
        ///				&quot;type&quot;:&quot;Key&quot;,
        ///				&quot;key&quot;:&quot;true&quot;
        ///			}
        ///		],
        ///		&quot;empty&quot;:false
        ///	},
        ///	&quot;uint&quot;:{
        ///		&quot;type&quot;:&quot;Join&quot;,
        ///		&quot;task&quot;:{
        ///			&quot;type&quot;:&quot;Symbol&quot;,
        ///			&quot;key&quot;:&quot;0123456789&quot;
        ///		},
        ///		&quot;min&quot;:1,
        ///		&quot;select&quot;:false
        ///	},
        ///	&quot;int&quot;:{
        ///		&quot;type&quot;:&quot;Option&quot;,
        ///		&quot;options&quot;:[
        ///			{
        ///				&quot;type&quot;:&quot;Symbol&quot;,
        ///				&quot;key&quot;:&quot;+-&quot;
        ///			}
        ///		],
        ///		&quot;task&quot;:&quot;uint&quot;,
        ///		&quot;empty&quot;:true
        ///	},
        ///	&quot;strin [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;Name&quot;:{
        ///        &quot;type&quot;:&quot;Stream&quot;,
        ///        &quot;tasks&quot;:[
        ///            {
        ///                &quot;type&quot;:&quot;Symbol&quot;,
        ///                &quot;key&quot;:&quot;@&quot;
        ///            },
        ///            {
        ///                &quot;type&quot;:&quot;Value&quot;,
        ///                &quot;key&quot;:&quot;@&quot;
        ///            },
        ///            {
        ///                &quot;type&quot;:&quot;Symbol&quot;,
        ///                &quot;key&quot;:&quot;@&quot;
        ///            }
        ///        ]
        ///    },
        ///    &quot;Space&quot;:{
        ///        &quot;type&quot;:&quot;Symbol&quot;,
        ///        &quot;key&quot;:&quot; &quot;
        ///    },
        ///    &quot;Key&quot;:{
        ///        &quot;type&quot;:&quot;Stream&quot;,
        ///        &quot;tasks&quot;:[
        ///            {
        ///                 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Parser {
            get {
                return ResourceManager.GetString("Parser", resourceCulture);
            }
        }
    }
}
